import '@/styles/global.css';
import '@/styles/theme.css';
import '@/styles/font.css';
import type { Metadata } from 'next';
import { ApolloWrapper } from '@/apollo/apollo-wrapper';
import suit from '@/suit';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  head?: React.ReactNode;
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <ApolloWrapper>
        <head></head>
        <body className={`${suit.className}`}>{children}</body>
      </ApolloWrapper>
    </html>
  );
}
