import './globals.css';
import type { Metadata } from 'next';
import { ApolloWrapper } from '@/apollo/apollo-wrapper';
import { fontGlobalStyles } from '@/styles/font.style';
import { globalStyles } from '@/styles/Global.style';
import suit from '@/suit';
import { getCssText } from '../../stitches.config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  head?: React.ReactNode;
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  fontGlobalStyles();
  globalStyles();
  return (
    <html lang="ko">
      <ApolloWrapper>
        <head>
          <style
            id="stitches"
            dangerouslySetInnerHTML={{ __html: getCssText() }}
          />
        </head>
        <body className={suit.className}>{children}</body>
      </ApolloWrapper>
    </html>
  );
}
