import './globals.css';
import { ApolloProvider } from '@apollo/client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import apolloClient from '@/apollo-client';
import { getCssText } from '../../stitches.config';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApolloProvider client={apolloClient}>
      <html lang="ko">
        <head>
          <style
            id="stitches"
            dangerouslySetInnerHTML={{ __html: getCssText() }}
          />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ApolloProvider>
  );
}
